# https://taskfile.dev

version: '3'

env:
  DIST_FOLDER: dist

tasks:
  build-all:
    cmds:
      - task: delete-dist
      - task: build-ts
      - task: copy-html
      - task: build-css
      - task: format-files
      - task: clean-dist
      - echo 🎉 All project files were fully built! 🎉
    silent: true

  build-static:
    cmds:
      - task: copy-html
      - task: build-css
      - task: clean-dist
      - echo 🎉 Static project files were built! 🎉
    silent: true

  build-css:
    cmds:
      # Transpile Sass files to CSS
      - echo 🎨 Transpiling Sass files to CSS...
      - sass src/public/style/global.scss:dist/style/style.css --style compressed
    silent: true

  build-ts:
    cmds:
      # Transpile TypeScript files into JavaScript
      - echo 💬 Transpiling TypeScript files...
      - tsc
      # Bundle all file in one JavaScript file
      - echo 📦 Bundling files...
      - npx rollup $DIST_FOLDER/main.js --file $DIST_FOLDER/main.js --format iife
    silent: true

  copy-html:
    cmds:
      # Copy static HTML files to dist folder
      - echo 📁 Copying static HTML files...
      - mkdir -p dist
      - cp -r src/public/** dist/
    silent: true

  clean-dist:
    cmds:
      # Clean unnecessary files in the dist folder
      - echo 🧽 Cleanning up unnecessary files...
      - rm -f dist/style/*.{scss,map}
    silent: true

  format-files:
    cmds:
      # Format the final code
      - echo ✨ Formatting the final code...
      - npm run --silent format
    silent: true

  delete-dist:
    cmds:
      - rm -fr $DIST_FOLDER
    silent: true
